version: "3"

services:
  db:
    image: "mysql/mysql-server:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=citizens
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - mysqldbvol:/var/lib/mysql

volumes:
  mysqldbvol: